<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class HouseSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('houses')->insert([
            [
                'name' => 'Gohomy1',
                'address' => '32 Ngõ 250 Kim Giang',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 12,
                'district_id' => 7,
                'ward_id' => 86,
            ],
            [
                'name' => 'Gohomy2',
                'address' => '6/16/250 Kim Giang',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 12,
                'district_id' => 7,
                'ward_id' => 86,
            ],
            [
                'name' => 'Gohomy3',
                'address' => '56/250 Kim Giang',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 12,
                'district_id' => 7,
                'ward_id' => 86,
            ],
            [
                'name' => 'HappyHome1',
                'address' => 'Số 8 Giảng Võ ',
                'electric_price' => 4000,
                'water_price' => 30000,
                'user_id' => 13,
                'district_id' => 1,
                'ward_id' => 4,
            ],
            [
                'name' => 'HappyHome2',
                'address' => 'Số 2/78 Kim Mã ',
                'electric_price' => 4000,
                'water_price' => 30000,
                'user_id' => 13,
                'district_id' => 1,
                'ward_id' => 5,
            ],         
            [
                'name' => 'HappyHome3',
                'address' => 'Số 50/10 Liễu Giai ',
                'electric_price' => 4000,
                'water_price' => 30000,
                'user_id' => 13,
                'district_id' => 1,
                'ward_id' => 6,
            ],  
            [
                'name' => 'FunnyHome1',
                'address' => 'Số 6 Hàng Mã',
                'electric_price' => 4000,
                'water_price' => 30000,
                'user_id' => 14,
                'district_id' => 2,
                'ward_id' => 24,
            ],
            [
                'name' => 'FunnyHome2',
                'address' => 'Số 10 Lý Thái Tổ',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 14,
                'district_id' => 2,
                'ward_id' => 26,
            ],
            [
                'name' => 'FunnyHome3',
                'address' => 'Số 6 Trần Hưng Đạo',
                'electric_price' => 4000,
                'water_price' => 25000,
                'user_id' => 14,
                'district_id' => 2,
                'ward_id' => 28,
            ],
            [
                'name' => 'THHome1',
                'address' => 'Số 6 Phố Huế',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 15,
                'district_id' => 3,
                'ward_id' => 37,
            ],
            [
                'name' => 'THHome2',
                'address' => 'Số 50 Minh Khai',
                'electric_price' => 4000,
                'water_price' => 25000,
                'user_id' => 15,
                'district_id' => 3,
                'ward_id' => 35,
            ],
            [
                'name' => 'THHome3',
                'address' => 'Số 10 Nguyễn Du',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 15,
                'district_id' => 3,
                'ward_id' => 36,
            ],
            [
                'name' => 'SunnyHome1',
                'address' => 'Số 10/78 Khâm Thiên',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 16,
                'district_id' => 4,
                'ward_id' => 43,
            ],
            [
                'name' => 'SunnyHome2',
                'address' => 'Số 10 Phương Mai',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 16,
                'district_id' => 4,
                'ward_id' => 52,
            ],
            [
                'name' => 'SunnyHome3',
                'address' => 'Số 20 Thái Hà',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 16,
                'district_id' => 4,
                'ward_id' => 57,
            ],
            [
                'name' => 'GHome1',
                'address' => 'Số 10 Kiến Hưng',
                'electric_price' => 3000,
                'water_price' => 20000,
                'user_id' => 17,
                'district_id' => 5,
                'ward_id' => 63,
            ],
            [
                'name' => 'GHome2',
                'address' => 'Số 10 Quang Trung',
                'electric_price' => 3000,
                'water_price' => 20000,
                'user_id' => 17,
                'district_id' => 5,
                'ward_id' => 69,
            ],
            [
                'name' => 'GHome3',
                'address' => 'Số 100 Văn Quán',
                'electric_price' => 3000,
                'water_price' => 25000,
                'user_id' => 17,
                'district_id' => 5,
                'ward_id' => 71,
            ],
            [
                'name' => 'FHome1',
                'address' => 'Số 10 Trung Hòa',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 18,
                'district_id' => 6,
                'ward_id' => 80,
            ],
            [
                'name' => 'FHome2',
                'address' => 'Số 5 Cầu Giấy',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 18,
                'district_id' => 6,
                'ward_id' => 79,
            ],
            [
                'name' => 'FHome3',
                'address' => 'Số 250 Mai Dịch',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 18,
                'district_id' => 6,
                'ward_id' => 76,
            ],
            [
                'name' => 'SHHome1',
                'address' => 'Số 10 Mễ Trì',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 19,
                'district_id' => 8,
                'ward_id' => 95,
            ],
            [
                'name' => 'SHHome2',
                'address' => 'Số 25 Phú Đô',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 19,
                'district_id' => 8,
                'ward_id' => 98,
            ],
            [
                'name' => 'SHHome3',
                'address' => 'Số 10/78/63 Phương Canh',
                'electric_price' => 3000,
                'water_price' => 20000,
                'user_id' => 19,
                'district_id' => 8,
                'ward_id' => 99,
            ],
            [
                'name' => 'LBHome1',
                'address' => 'Số 10 Ngọc Lâm',
                'electric_price' => 3000,
                'water_price' => 15000,
                'user_id' => 20,
                'district_id' => 9,
                'ward_id' => 107,
            ],
            [
                'name' => 'LBHome2',
                'address' => 'Số 70 Thạch Bàn',
                'electric_price' => 3000,
                'water_price' => 15000,
                'user_id' => 20,
                'district_id' => 9,
                'ward_id' => 110,
            ],
            [
                'name' => 'EmilyHome1',
                'address' => 'Số 10 Định Công',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 21,
                'district_id' => 10,
                'ward_id' => 113,
            ],
            [
                'name' => 'EmilyHome2',
                'address' => 'Số 100 Giáp Bát',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 21,
                'district_id' => 10,
                'ward_id' => 114,
            ],
            [
                'name' => 'EmilyHome3',
                'address' => 'Số 2 Yên Sở',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 21,
                'district_id' => 10,
                'ward_id' => 125,
            ],
            [
                'name' => 'AHAHome1',
                'address' => 'Số 10 Phú Diễn',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 22,
                'district_id' => 11,
                'ward_id' => 132,
            ],
            [
                'name' => 'AHAHome2',
                'address' => 'Số 10/150 Xuân Đỉnh',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 22,
                'district_id' => 11,
                'ward_id' => 135,
            ],
            [
                'name' => 'AHAHome3',
                'address' => 'Số 2 Cổ Nhuế',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 22,
                'district_id' => 11,
                'ward_id' => 126,
            ],
            [
                'name' => 'HELLOHome1',
                'address' => 'Số 2 đường Bưởi',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 23,
                'district_id' => 12,
                'ward_id' => 137,
            ],
            [
                'name' => 'HELLOHome2',
                'address' => 'Số 10 Quảng An',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 23,
                'district_id' => 12,
                'ward_id' => 140,
            ],
            [
                'name' => 'HELLOHome3',
                'address' => 'Số 20 Tứ Liên',
                'electric_price' => 3800,
                'water_price' => 25000,
                'user_id' => 23,
                'district_id' => 12,
                'ward_id' => 142,
            ],

        ]);
    }
}
