<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class PostSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('posts')->insert([
            [
                'user_id' => '1',
                'title' => 'Tìm phòng gần Lotte Liễu Giai',
                'district_id' => '1',
                'ward_id' => '1',
                'room_type' => 'trọ thường',
                'max_people' => '2',
                'price' => '2000000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,có ban công',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '1',
                'title' => 'Tìm phòng gần đại học Giao Thông Vận Tải',
                'district_id' => '1',
                'ward_id' => '8',
                'room_type' => 'trọ thường',
                'max_people' => '3',
                'price' => '2500000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,có ban công,ở tầng cao',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '1',
                'title' => 'Tìm phòng gần hồ Giảng Võ',
                'district_id' => '1',
                'ward_id' => '4',
                'room_type' => 'trọ thường',
                'max_people' => '3',
                'price' => '3000000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '2',
                'title' => 'Tìm phòng gần hồ Gươm',
                'district_id' => '2',
                'ward_id' => '26',
                'room_type' => 'chung cư mini',
                'max_people' => '4',
                'price' => '4500000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '2',
                'title' => 'Tìm phòng rộng cho 4 khách nước ngoài',
                'district_id' => '2',
                'ward_id' => '24',
                'room_type' => 'chung cư mini',
                'max_people' => '4',
                'price' => '6000000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '3',
                'title' => 'Tìm phòng gần đại học Bách Khoa',
                'district_id' => '3',
                'ward_id' => '31',
                'room_type' => 'trọ thường',
                'max_people' => '3',
                'price' => '3000000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '3',
                'title' => 'Tìm phòng gần đại học Kinh Tế Quốc Dân',
                'district_id' => '3',
                'ward_id' => '33',
                'room_type' => 'trọ thường',
                'max_people' => '2',
                'price' => '2500000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '3',
                'title' => 'Tìm phòng quanh công viên Thống Nhất',
                'district_id' => '3',
                'ward_id' => '34',
                'room_type' => 'trọ thường',
                'max_people' => '2',
                'price' => '2200000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '4',
                'title' => 'Tìm phòng quanh đại học Thủy Lợi',
                'district_id' => '4',
                'ward_id' => '57',
                'room_type' => 'trọ thường',
                'max_people' => '3',
                'price' => '3000000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '4',
                'title' => 'Tìm phòng quanh đại Học Viện Ngân Hàng',
                'district_id' => '4',
                'ward_id' => '53',
                'room_type' => 'chung cư mini',
                'max_people' => '4',
                'price' => '4500000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '4',
                'title' => 'Tìm phòng gần đại học Y Hà Nội',
                'district_id' => '4',
                'ward_id' => '45',
                'room_type' => 'trọ thường',
                'max_people' => '3',
                'price' => '2800000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '5',
                'title' => 'Tìm phòng giá rẻ gần đại học Kiến Trúc',
                'district_id' => '5',
                'ward_id' => '71',
                'room_type' => 'trọ thường',
                'max_people' => '2',
                'price' => '2200000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '5',
                'title' => 'Tìm phòng quanh hồ Văn Quán',
                'district_id' => '5',
                'ward_id' => '71',
                'room_type' => 'chung cư mini',
                'max_people' => '2',
                'price' => '4000000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '6',
                'title' => 'Tìm phòng gần đại học Sư Phạm Hà Nội',
                'district_id' => '6',
                'ward_id' => '75',
                'room_type' => 'chung cư mini',
                'max_people' => '3',
                'price' => '4500000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ],
            [
                'user_id' => '6',
                'title' => 'Tìm phòng trên đường Cầu Giấy',
                'district_id' => '6',
                'ward_id' => '79',
                'room_type' => 'chung cư mini',
                'max_people' => '3',
                'price' => '3500000',
                'description' => 'Tìm phòng có điều hòa,nóng lạnh,vệ sinh khép kín,đầy đủ phòng cháy chữa cháy',
                'status' => 'approved',
                'created_at' => now(),
                'updated_at' => now(),
            ]
        ]);
    }
}
