<?php

namespace Database\Seeders;

use Illuminate\Database\Console\Seeds\WithoutModelEvents;
use Illuminate\Database\Seeder;
use Illuminate\Support\Facades\DB;

class WardSeeder extends Seeder
{
    /**
     * Run the database seeds.
     */
    public function run(): void
    {
        DB::table('wards')->insert([
            ['name' => 'Phường Cống Vị', 'district_id' => 1],
            ['name' => 'Phường Điện Biên', 'district_id' => 1],
            ['name' => 'Phường Đội Cấn', 'district_id' => 1],
            ['name' => 'Phường Giảng Võ', 'district_id' => 1],
            ['name' => 'Phường Kim Mã', 'district_id' => 1],
            ['name' => 'Phường Liễu Giai', 'district_id' => 1],
            ['name' => 'Phường Ngọc Hà', 'district_id' => 1],
            ['name' => 'Phường Ngọc Khánh', 'district_id' => 1],
            ['name' => 'Phường Nguyễn Trung Trực', 'district_id' => 1],
            ['name' => 'Phường Phúc Xá', 'district_id' => 1],
            ['name' => 'Phường Quán Thánh', 'district_id' => 1],
            ['name' => 'Phường Thành Công', 'district_id' => 1],
            ['name' => 'Phường Trúc Bạch', 'district_id' => 1],
            ['name' => 'Phường Vĩnh Phúc', 'district_id' => 1],
            ['name' => 'Phường Chương Dương', 'district_id' => 2],
            ['name' => 'Phường Cửa Đông', 'district_id' => 2],
            ['name' => 'Phường Cửa Nam', 'district_id' => 2],
            ['name' => 'Phường Đồng Xuân', 'district_id' => 2],
            ['name' => 'Phường Hàng Bạc', 'district_id' => 2],
            ['name' => 'Phường Hàng Bài', 'district_id' => 2],
            ['name' => 'Phường Hàng Bông', 'district_id' => 2],
            ['name' => 'Phường Hàng Đào', 'district_id' => 2],
            ['name' => 'Phường Hàng Gai', 'district_id' => 2],
            ['name' => 'Phường Hàng Mã', 'district_id' => 2],
            ['name' => 'Phường Hàng Trống', 'district_id' => 2],
            ['name' => 'Phường Lý Thái Tổ', 'district_id' => 2],
            ['name' => 'Phường Phan Chu Trinh', 'district_id' => 2],
            ['name' => 'Phường Trần Hưng Đạo', 'district_id' => 2],
            ['name' => 'Phường Tràng Tiền', 'district_id' => 2],
            ['name' => 'Phường Bạch Đằng', 'district_id' => 3],
            ['name' => 'Phường Bách Khoa', 'district_id' => 3],
            ['name' => 'Phường Bạch Mai', 'district_id' => 3],
            ['name' => 'Phường Đồng Tâm', 'district_id' => 3],
            ['name' => 'Phường Lê Đại Hành', 'district_id' => 3],
            ['name' => 'Phường Minh Khai', 'district_id' => 3],
            ['name' => 'Phường Nguyễn Du', 'district_id' => 3],
            ['name' => 'Phường Phố Huế', 'district_id' => 3],
            ['name' => 'Phường Thanh Nhàn', 'district_id' => 3],
            ['name' => 'Phường Trương Định', 'district_id' => 3],
            ['name' => 'Phường Vĩnh Tuy', 'district_id' => 3],
            ['name' => 'Phường Cát Linh', 'district_id' => 4],
            ['name' => 'Phường Hàng Bột', 'district_id' => 4],
            ['name' => 'Phường Khâm Thiên', 'district_id' => 4],
            ['name' => 'Phường Khương Thượng', 'district_id' => 4],
            ['name' => 'Phường Kim Liên', 'district_id' => 4],
            ['name' => 'Phường Láng Hạ', 'district_id' => 4],
            ['name' => 'Phường Láng Thượng', 'district_id' => 4],
            ['name' => 'Phường Nam Đồng', 'district_id' => 4],
            ['name' => 'Phường Ngã Tư Sở', 'district_id' => 4],
            ['name' => 'Phường Ô Chợ Dừa', 'district_id' => 4],
            ['name' => 'Phường Phương Liên', 'district_id' => 4],
            ['name' => 'Phường Phương Mai', 'district_id' => 4],
            ['name' => 'Phường Quang Trung', 'district_id' => 4],
            ['name' => 'Phường Quốc Tử Giám', 'district_id' => 4],
            ['name' => 'Phường Thịnh Quang', 'district_id' => 4],
            ['name' => 'Phường Thổ Quan', 'district_id' => 4],
            ['name' => 'Phường Trung Liệt', 'district_id' => 4],
            ['name' => 'Phường Trung Tự', 'district_id' => 4],
            ['name' => 'Phường Văn Chương', 'district_id' => 4],
            ['name' => 'Phường Văn Miếu', 'district_id' => 4],
            ['name' => 'Phường Dương Nội', 'district_id' => 5],
            ['name' => 'Phường Hà Cầu', 'district_id' => 5],
            ['name' => 'Phường Kiến Hưng', 'district_id' => 5],
            ['name' => 'Phường La Khê', 'district_id' => 5],
            ['name' => 'Phường Mộ Lao', 'district_id' => 5],
            ['name' => 'Phường Nguyễn Trãi', 'district_id' => 5],
            ['name' => 'Phường Phú La', 'district_id' => 5],
            ['name' => 'Phường Phúc La', 'district_id' => 5],
            ['name' => 'Phường Quang Trung', 'district_id' => 5],
            ['name' => 'Phường Vạn Phúc', 'district_id' => 5],
            ['name' => 'Phường Văn Quán', 'district_id' => 5],
            ['name' => 'Phường Yên Nghĩa', 'district_id' => 5],
            ['name' => 'Phường Yết Kiêu', 'district_id' => 5],
            ['name' => 'Phường Dịch Vọng', 'district_id' => 6],
            ['name' => 'Phường Dịch Vọng Hậu', 'district_id' => 6],
            ['name' => 'Phường Mai Dịch', 'district_id' => 6],
            ['name' => 'Phường Nghĩa Đô', 'district_id' => 6],
            ['name' => 'Phường Nghĩa Tân', 'district_id' => 6],
            ['name' => 'Phường Quan Hoa', 'district_id' => 6],
            ['name' => 'Phường Trung Hòa', 'district_id' => 6],
            ['name' => 'Phường Yên Hòa', 'district_id' => 6],
            ['name' => 'Phường Hạ Đình', 'district_id' => 7],
            ['name' => 'Phường Khương Đình', 'district_id' => 7],
            ['name' => 'Phường Khương Mai', 'district_id' => 7],
            ['name' => 'Phường Khương Trung', 'district_id' => 7],
            ['name' => 'Phường Kim Giang', 'district_id' => 7],
            ['name' => 'Phường Nhân Chính', 'district_id' => 7],
            ['name' => 'Phường Phương Liệt', 'district_id' => 7],
            ['name' => 'Phường Thanh Xuân Bắc', 'district_id' => 7],
            ['name' => 'Phường Thanh Xuân Nam', 'district_id' => 7],
            ['name' => 'Phường Thanh Xuân Trung', 'district_id' => 7],
            ['name' => 'Phường Thượng Đình', 'district_id' => 7],
            ['name' => 'Phường Cầu Diễn', 'district_id' => 8],
            ['name' => 'Phường Đại Mỗ', 'district_id' => 8],
            ['name' => 'Phường Mễ Trì', 'district_id' => 8],
            ['name' => 'Phường Mỹ Đình 1', 'district_id' => 8],
            ['name' => 'Phường Mỹ Đình 2', 'district_id' => 8],
            ['name' => 'Phường Phú Đô', 'district_id' => 8],
            ['name' => 'Phường Phương Canh', 'district_id' => 8],
            ['name' => 'Phường Tây Mỗ', 'district_id' => 8],
            ['name' => 'Phường Trung Văn', 'district_id' => 8],
            ['name' => 'Phường Xuân Phương', 'district_id' => 8],
            ['name' => 'Phường Bồ Đề', 'district_id' => 9],
            ['name' => 'Phường Đức Giang', 'district_id' => 9],
            ['name' => 'Phường Gia Thụy', 'district_id' => 9],
            ['name' => 'Phường Long Biên', 'district_id' => 9],
            ['name' => 'Phường Ngọc Lâm', 'district_id' => 9],
            ['name' => 'Phường Ngọc Thụy', 'district_id' => 9],
            ['name' => 'Phường Sài Đồng', 'district_id' => 9],
            ['name' => 'Phường Thạch Bàn', 'district_id' => 9],
            ['name' => 'Phường Việt Hưng', 'district_id' => 9],
            ['name' => 'Phường Đại Kim', 'district_id' => 10],
            ['name' => 'Phường Định Công', 'district_id' => 10],
            ['name' => 'Phường Giáp Bát', 'district_id' => 10],
            ['name' => 'Phường Hoàng Liệt', 'district_id' => 10],
            ['name' => 'Phường Hoàng Văn Thụ', 'district_id' => 10],
            ['name' => 'Phường Lĩnh Nam', 'district_id' => 10],
            ['name' => 'Phường Mai Động', 'district_id' => 10],
            ['name' => 'Phường Tân Mai', 'district_id' => 10],
            ['name' => 'Phường Thanh Trì', 'district_id' => 10],
            ['name' => 'Phường Thịnh Liệt', 'district_id' => 10],
            ['name' => 'Phường Trần Phú', 'district_id' => 10],
            ['name' => 'Phường Tương Mai', 'district_id' => 10],
            ['name' => 'Phường Vĩnh Hưng', 'district_id' => 10],
            ['name' => 'Phường Yên Sở', 'district_id' => 10],
            ['name' => 'Phường Cổ Nhuế 1', 'district_id' => 11],
            ['name' => 'Phường Cổ Nhuế 2', 'district_id' => 11],
            ['name' => 'Phường Đông Nhạc', 'district_id' => 11],
            ['name' => 'Phường Đức Thắng', 'district_id' => 11],
            ['name' => 'Phường Liên Mạc', 'district_id' => 11],
            ['name' => 'Phường Minh Khai', 'district_id' => 11],
            ['name' => 'Phường Phú Diễn', 'district_id' => 11],
            ['name' => 'Phường Phúc Diễn', 'district_id' => 11],
            ['name' => 'Phường Tây Tựu', 'district_id' => 11],
            ['name' => 'Phường Xuân Đỉnh', 'district_id' => 11],
            ['name' => 'Phường Xuân Tảo', 'district_id' => 11],
            ['name' => 'Phường Bưởi', 'district_id' => 12],
            ['name' => 'Phường Nhật Tân', 'district_id' => 12],
            ['name' => 'Phường Phú Thượng', 'district_id' => 12],
            ['name' => 'Phường Quảng An', 'district_id' => 12],
            ['name' => 'Phường Thụy Khuê', 'district_id' => 12],
            ['name' => 'Phường Tứ Liên', 'district_id' => 12],
            ['name' => 'Phường Xuân La', 'district_id' => 12],
            ['name' => 'Phường Yên Phụ', 'district_id' => 12],
        ]);
    }
}
